// Export other services as they're created
export * from './admin.service';
export * from './appointment.service';
export * from './cache.service';
export * from './clinic.service';
export * from './doctor.service';
export * from './growth.service';
export * from './immunization/due-calculator';
export * from './index';
export * from './lab-test.service';
export * from './medical.service';
export { MedicalService, medicalService } from './medical.service';
export * from './medical-record.service';
export * from './patient.service';
export * from './payment.service';
export * from './prescription.service';
export * from './service.services';
export * from './staff.service';
export * from './system.service';
export * from './vaccination.service';
export * from './visit.service';
export * from './vitals.service';
