// server/api/routers/staff.ts

import { TRPCError } from '@trpc/server';
import { headers } from 'next/headers';
import z from 'zod';

import { staffCreateSchema, staffUpdateSchema } from '../../../zodSchemas';
import { auth } from '../../auth';
import { staffService } from '../../db/services';
import { adminProcedure, createTRPCRouter, publicProcedure } from '..';
import { generateId } from '../utils/id';

const createStaff = staffCreateSchema.extend({
  password: z.string()
});

export const staffRouter = createTRPCRouter({
  // -----------------------------------------------------
  // 1. getAllStaff (Paginated List)
  // -----------------------------------------------------
  // getAllStaff: publicProcedure.input(GetAllStaffSchema).query(async ({ input }) => {
  //   const clinicId = ''; // This should ideally come from ctx.session?.user.clinic?.id
  //   return await staffService.getAllStaff(clinicId, {
  //     page: input.page,
  //     limit: input.limit,
  //     search: input.search
  //   });
  // }),

  /**
   * Create new staff member
   * 1. Creates auth user via Better Auth
   * 2. Creates staff record linked to auth ID via service
   */
  createNewStaff: adminProcedure.input(createStaff).mutation(async ({ input, ctx }) => {
    try {
      const clinicId = ctx.session?.user.clinic?.id;
      if (!clinicId) {
        throw new TRPCError({
          code: 'UNAUTHORIZED',
          message: 'Clinic ID not found'
        });
      }

      // 1. Create Auth User via Better Auth API
      const newUser = await auth.api.createUser({
        body: {
          email: input.email,
          password: input.password,
          name: input.name,
          role: 'staff',
          data: {
            role: input.role
          }
        },
        headers: await headers()
      });

      if (!newUser?.user?.id) {
        throw new Error('Auth user creation failed');
      }

      // 2. Create Staff Record via service (scoped to clinic)
      const staff = await staffService.createStaff(clinicId, {
        id: generateId(),
        clinicId,
        userId: newUser.user.id,
        name: input.name,
        phone: input.phone,
        email: input.email,
        role: input.role,
        img: input.img,
        hireDate: input.hireDate,
        licenseNumber: input.licenseNumber,
        salary: input.salary,
        address: input.address,
        department: input.department
        // colorCode is generated by service
      });

      return {
        success: true,
        message: 'Staff member added successfully',
        data: staff
      };
    } catch (error) {
      console.error('[createNewStaff]', error);
      throw new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: error instanceof Error ? error.message : 'Failed to add staff member.'
      });
    }
  }),

  /**
   * Update staff member
   * Delegates to staff service with clinic scope
   */
  updateStaff: adminProcedure.input(staffUpdateSchema).mutation(async ({ input, ctx }) => {
    try {
      const clinicId = ctx.session?.user.clinic?.id;
      if (!clinicId) {
        throw new TRPCError({
          code: 'UNAUTHORIZED',
          message: 'Clinic ID not found'
        });
      }

      const { id, ...data } = input;

      // Verify staff exists and belongs to clinic
      const existing = await staffService.getStaffById(id, clinicId).catch(() => null);
      if (!existing) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Staff member not found'
        });
      }

      const updated = await staffService.updateStaff(id, clinicId, data);

      return {
        success: true,
        data: updated
      };
    } catch (error) {
      console.error('[updateStaff]', error);
      if (error instanceof TRPCError) throw error;
      throw new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to update staff member.'
      });
    }
  }),

  /**
   * Delete staff member
   * Delegates to staff service with clinic scope
   */
  deleteStaff: adminProcedure.input(z.object({ id: z.string().uuid() })).mutation(async ({ input, ctx }) => {
    try {
      const clinicId = ctx.session?.user.clinic?.id;
      if (!clinicId) {
        throw new TRPCError({
          code: 'UNAUTHORIZED',
          message: 'Clinic ID not found'
        });
      }

      // Verify staff exists and belongs to clinic
      const existing = await staffService.getStaffById(input.id, clinicId).catch(() => null);
      if (!existing) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Staff member not found'
        });
      }

      await staffService.deleteStaff(input.id, clinicId);

      return {
        success: true,
        message: 'Staff member deleted successfully'
      };
    } catch (error) {
      console.error('[deleteStaff]', error);
      if (error instanceof TRPCError) throw error;
      throw new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to delete staff member.'
      });
    }
  }),

  /**
   * Get staff by ID
   * Public procedure with clinic scope validation
   */
  getStaffById: publicProcedure.input(z.object({ id: z.string().uuid() })).query(async ({ input, ctx }) => {
    try {
      const clinicId = ctx.session?.user.clinic?.id;
      if (!clinicId) {
        throw new TRPCError({
          code: 'UNAUTHORIZED',
          message: 'Clinic ID not found'
        });
      }

      const staff = await staffService.getStaffById(input.id, clinicId);

      return {
        success: true,
        data: staff
      };
    } catch (error) {
      console.error('[getStaffById]', error);
      if (error instanceof Error && error.message === 'Staff member not found') {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Staff member not found.'
        });
      }
      throw new TRPCError({
        code: 'INTERNAL_SERVER_ERROR',
        message: 'Failed to retrieve staff member.'
      });
    }
  }),

  /**
   * Get all staff for clinic
   * With pagination and search
   */
  getAllStaff: adminProcedure
    .input(
      z.object({
        page: z.number().int().min(1).default(1),
        limit: z.number().int().min(1).max(100).default(20),
        search: z.string().optional()
      })
    )
    .query(async ({ input, ctx }) => {
      try {
        const clinicId = ctx.session?.user.clinic?.id;
        if (!clinicId) {
          throw new TRPCError({
            code: 'UNAUTHORIZED',
            message: 'Clinic ID not found'
          });
        }

        return await staffService.getAllStaff(clinicId, {
          page: input.page,
          limit: input.limit,
          search: input.search
        });
      } catch (error) {
        console.error('[getAllStaff]', error);
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to retrieve staff list.'
        });
      }
    })
});
